export const quizData = [
  {
    id: 1,
    category: "General Knowledge",
    question: "What is the capital of France?",
    options: ["London", "Berlin", "Paris", "Madrid"],
    answer: "Paris",
  },
  {
    id: 2,
    category: "Science",
    question: "What is the chemical symbol for water?",
    options: ["H2O", "O2", "NaCl", "CO2"],
    answer: "H2O",
  },
  {
    id: 3,
    category: "Technology",
    question: "Which company developed the React library?",
    options: ["Google", "Facebook", "Microsoft", "Apple"],
    answer: "Facebook",
  },
  {
    id: 4,
    category: "Sports",
    question: "How many players are there in a soccer team on the field?",
    options: ["9", "10", "11", "12"],
    answer: "11",
  },
  {
    id: 5,
    category: "Mathematics",
    question: "What is the value of π (pi) approximately?",
    options: ["2.14", "3.14", "4.13", "3.41"],
    answer: "3.14",
  },
  {
    id: 6,
    category: "Geography",
    question: "Which is the largest ocean on Earth?",
    options: ["Atlantic", "Indian", "Arctic", "Pacific"],
    answer: "Pacific",
  },
  {
    id: 7,
    category: "Science",
    question: "What planet is known as the Red Planet?",
    options: ["Earth", "Venus", "Mars", "Jupiter"],
    answer: "Mars",
  },
  {
    id: 8,
    category: "Technology",
    question: "What does HTML stand for?",
    options: [
      "Hyper Trainer Marking Language",
      "Hyper Text Markup Language",
      "Hyper Text Marketing Language",
      "Hyper Tool Multi Language",
    ],
    answer: "Hyper Text Markup Language",
  },
  {
    id: 9,
    category: "Sports",
    question: "Who won the FIFA World Cup in 2018?",
    options: ["Brazil", "Germany", "France", "Argentina"],
    answer: "France",
  },
  {
    id: 10,
    category: "History",
    question: "Who was the first President of the United States?",
    options: [
      "Thomas Jefferson",
      "Abraham Lincoln",
      "George Washington",
      "John Adams",
    ],
    answer: "George Washington",
  },
  {
    id: 11,
    category: "Entertainment",
    question: "Which movie won the Oscar for Best Picture in 2023?",
    options: [
      "Top Gun: Maverick",
      "Avatar: The Way of Water",
      "Everything Everywhere All at Once",
      "The Fabelmans",
    ],
    answer: "Everything Everywhere All at Once",
  },
  {
    id: 12,
    category: "Maths",
    question: "What is 12 × 8?",
    options: ["96", "84", "108", "88"],
    answer: "96",
  },
  {
    id: 13,
    category: "General Knowledge",
    question: "Which is the smallest country in the world?",
    options: ["Monaco", "Vatican City", "Malta", "San Marino"],
    answer: "Vatican City",
  },
  {
    id: 14,
    category: "Science",
    question: "Which gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    answer: "Carbon Dioxide",
  },
  {
    id: 15,
    category: "Technology",
    question: "What does CSS stand for?",
    options: [
      "Creative Style Sheets",
      "Computer Style Sheets",
      "Cascading Style Sheets",
      "Colorful Style Sheets",
    ],
    answer: "Cascading Style Sheets",
  },
];

export default quizData;
